@url = http://127.0.0.1:3000/api/user
@token = 


###
GET {{url}}/ping


###
GET {{url}}/users
###
GET {{url}}/users/?page_size=10&page_index=2&keywords=
###
GET {{url}}/users
Authorization: Bearer {{token}}


###
GET {{url}}/me
Authorization: Bearer {{token}}


###
POST {{url}}/register
Content-Type: application/json

{
  "name": "fluffy2",
  "password": "123456"
}


###
POST {{url}}/login
Content-Type: application/json

{
  "name": "fluffy1",
  "password": "123456"
}
###
POST {{url}}/login
Content-Type: application/json

{
  "name": "fluffy2",
  "password": "123456"
}

###
POST {{url}}/login
Content-Type: application/json

{
  "name": "fluffy1",
  "password": "12345678"
}

###
POST {{url}}/login
Content-Type: application/json

{
  "name": "fluffy3",
  "password": "123456",
  "email": "fluffy3@example.com"
}

###
POST {{url}}/login
Content-Type: application/json

{
}


###
POST {{url}}/update


